# Generated by Django 5.0 on 2024-06-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email')),
                ('is_subscribed', models.BooleanField(default=True, verbose_name='subscribed')),
                ('date_recieved', models.DateTimeField(auto_now_add=True, verbose_name='date recieved')),
                ('date_last_viewed', models.DateTimeField(auto_now=True, verbose_name='last viewed')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='date_last_viewed',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last viewed'),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_recieved',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date recieved'),
        ),
    ]
